repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff
        args: ["--fix"]
        stages: [pre-commit, pre-push]
      - id: ruff-format
        stages: [pre-commit, pre-push]